import assert from 'node:assert/strict';
import { createSessionWorkbench } from './sessionWorkbench.js';

let serialized = '';
const storage = { getItem: () => serialized, setItem: (_key, value) => { serialized = value; } };
let sequence = 0;
const state = createSessionWorkbench({ storage, newId: () => String(++sequence) });
const a = state.ownerFor({ sessionId: 'a', workspaceHash: 'same' });
const b = state.ownerFor({ sessionId: 'b', workspaceHash: 'same' });
assert.notEqual(a, b);
assert.equal(a, state.ownerFor({ sessionId: 'a', workspaceHash: 'same', cwd: '/worktree' }));
state.set(a, 'tree', new Map([['src', ['a.cpp']]]));
state.set(a, 'expanded', new Set(['src']));
state.set(b, 'expanded', new Set(['docs']));
assert.deepEqual(state.get(a, 'expanded'), new Set(['src']));
assert.deepEqual(state.get(b, 'expanded'), new Set(['docs']));
const lateUpdate = () => state.set(a, 'tree', new Map([['late', ['late.cpp']]]));
lateUpdate();
assert.equal(state.get(b, 'tree', null), null);
const draft = state.ownerFor({ workspaceHash: 'same' });
assert.equal(draft, state.ownerFor({ workspaceHash: 'same' }));
state.set(draft, 'tabs', ['first']);
assert.equal(state.transfer(draft, a), false);
assert.equal(state.transfer(draft, 'session:new'), true);
assert.deepEqual(state.get('session:new', 'tabs'), ['first']);
assert.notEqual(state.ownerFor({ workspaceHash: 'same' }), draft);
state.set(draft, 'tabs', (tabs) => [...tabs, 'late']);
assert.deepEqual(state.get('session:new', 'tabs'), ['first', 'late']);
assert.equal(state.transfer(draft, 'session:other'), false);
state.set(a, '$runtime', { callback() {} });
state.set(a, 'edit', { text: 'draft', baselineText: 'disk', saving: true });
// Simulate snapshots from before layout widths became a global preference.
state.set(a, 'layout', { sidebar: 180, sidePanel: 260 });
state.set(b, 'layout', { sidebar: 350, sidePanel: 480 });
state.set('session:new', 'layout', { sidebar: 240, sidePanel: 300 });
state.flush();
const restored = createSessionWorkbench({ storage });
assert.deepEqual(restored.entries('layout'), []);
assert.deepEqual(restored.get(a, 'expanded'), new Set(['src']));
assert.deepEqual(restored.get(a, 'tree'), new Map([['late', ['late.cpp']]]));
assert.equal(restored.get(a, 'edit').saving, false);
assert.equal(restored.get(a, '$runtime', null), null);
assert.equal(restored.resolve(draft), 'session:new');
assert.deepEqual(restored.get(b, 'expanded'), new Set(['docs']));
assert.deepEqual(restored.get('session:new', 'tabs'), ['first', 'late']);
restored.flush();
assert.ok(!serialized.includes('"layout":'));
console.log('[pass] old session layout widths are discarded without losing tabs, caches or ownership');
console.log('[pass] session workbench isolates owners, restores typed state and transfers only to a new session');
